language: python

os:
  - "linux"
  
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7" 
install:
  - pip install requests
  - pip install python-coveralls

script: 
  - coverage run --source='YaDiskClient' -m unittest discover -s tests -t tests
after_success:
  - coveralls